### ISSUE TITLE
Question about provisioning profiles

### ISSUE THREAD

**Issue by gerchicov-bp** [paulw11/CallKitTutorial#2]
@paulw11 
I have an existing project and try to add target "Call Directory Extension" to it with any code.
Is it obligatory to create app groups (which involves revoking all existing provisioning profiles) if I don't need to communicate with the main app or other app extensions?

**Comment by paulw11** [comment]
If you don't want to share any data between your main app and the extension then you don't need an app group, but how will your extension get its call identification or blocking data?
